Documentation updates for https://github.com/archivesunleashed/aut/pu…
archivesunleashed/aut-docs pull request #119
Opened 2022-06-14 17:11 UTC by ruebot

…ll/541

2022-06-16 18:39 UTC, ianmilligan1 requested changes
Ran through the docs, they look good. Only minor thing was a typo fix.

2022-06-16 18:39 UTC, ianmilligan1 commented on docs/home.md
> +- [Create the Archives Research Compiute Hub (ARCH) Derivatives](auk-derivatives.md)
Compiute -> Compute

2022-06-17 12:57 UTC, ianmilligan1 approved these changes

2022-06-17 14:29 UTC, SamFritz approved these changes
This looks great, wasn't able to find any issues/changes needed! Thank you @ruebot for all the updates to the documentation! Wonderful to documentation reflect this AUT milestone

2022-06-17 14:42 UTC, merged