Address https://github.com/archivesunleashed/aut/issues/372 - DRAFT
archivesunleashed/aut-docs pull request #39
Opened 2020-01-16 21:50 UTC by ruebot

Depends on https://github.com/archivesunleashed/aut/pull/406

2020-01-17 02:47 UTC, ianmilligan1 requested changes
Just did a prose review – caught a few things, @ruebot.

I haven't obviously in the few minutes this has been open gone through all of the scripts to test them. Do you want me to do that? (it might take into next week as things are a bit swamped right now)

2020-01-17 02:47 UTC, ianmilligan1 commented on current/README.md
> +This documentation is centred on a cookbook approach, providing a series of "recipes" for addressing a number of common analytics tasks, and inspiration for your own analysis. We generally provide ex
"is centred on a cookbook approach" -> "is based on a cookbook approach"
"and inspiration for your own analysis" -> "to provide inspiration for your own analysis"

2020-01-17 02:47 UTC, ianmilligan1 commented on current/binary-analysis.md
> +**Will not be implemented.**
👍

2020-01-17 02:47 UTC, ianmilligan1 commented on current/df-results.md
> +If you want to store the results with the intention to read the results back later for further processing, then use Parquet format:
Is there a good link out on "Parquet format" to an overview of what that means for somebody who wants to dig in further?

2020-01-17 02:47 UTC, ianmilligan1 commented on current/link-analysis.md
> -- [Export as TSV](#Export-as-TSV)
👍

2020-01-17 02:47 UTC, ianmilligan1 commented on current/rdd-results.md
> +FOr example, rchive records are represented in Spark as [tuples](https://en.wikipedia.org/wiki/Tuple),
"FOr example, rchive records" -> "For example, archive records"

2020-01-17 16:35 UTC, ianmilligan1 requested changes
Decided to bite the bullet and plow through this! Looks great, @ruebot - I've tested all the new scripts.

A few errors, which I've put in the comment. Three quarters of the docs refer to `example.arc.gz` and the other quarter to `example.warc.gz` - I'd be a fan of just using `example.arc.gz` as you'll see.

2020-01-17 16:35 UTC, ianmilligan1 commented on current/collection-analysis.md
> +  .show(10, false)
Tested ✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/collection-analysis.md
> +```
Tested ✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/collection-analysis.md
> +  .show(10, false)
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +  .saveAsTextFile("links-all-rdd/")
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
>  ```
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +  .write.csv("links-all-df/")
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +  .write.csv("links-all-apple-df/")
Getting an error

```
20/01/17 11:25:54 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
org.apache.spark.sql.AnalysisException: cannot resolve '`content`' given input columns: [crawl_date, src, dest, anchor];;
'Filter UDF('content)
+- LogicalRDD [crawl_date#127, src#128, dest#129, anchor#130], false
```

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +  .saveAsTextFile("full-links-all-rdd/")
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +```
Getting

```
org.apache.spark.sql.AnalysisException: cannot resolve '`src`' given input columns: [mime_type_tika, mime_type_web_server, content, crawl_date, language, url];;
'Aggregate [UDF('src), UDF('dest)], [UDF('src) AS UDF(src)#217, UDF('dest) AS UDF(dest)#218, count(1) AS count#216L]
+- LogicalRDD [crawl_date#197, url#198, mime_type_web_server#199, mime_type_tika#200, language#201, content#202], false
```

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +  .saveAsTextFile("details-links-all-rdd/")
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +```
```
org.apache.spark.sql.AnalysisException: cannot resolve '`src`' given input columns: [url, language, crawl_date, mime_type_tika, content, mime_type_web_server];;
'Aggregate [UDF(UDF('src)), UDF(UDF('dest))], [UDF(UDF('src)) AS UDF(UDF(src))#245, UDF(UDF('dest)) AS UDF(UDF(dest))#246, count(1) AS count#244L]
+- Filter UDF(url#226)
   +- LogicalRDD [crawl_date#225, url#226, mime_type_web_server#227, mime_type_tika#228, language#229, content#230], false
```

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +```
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/link-analysis.md
> +```
Error

```
org.apache.spark.sql.AnalysisException: cannot resolve '`url`' given input columns: [crawl_date, src, dest, anchor];;
'Filter UDF('url)
+- LogicalRDD [crawl_date#286, src#287, dest#288, anchor#289], false
```

2020-01-17 16:35 UTC, ianmilligan1 commented on current/standard-derivatives.md
> +  .write.csv("/path/to/derivatives/csv/audio")
These all check out! ✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +  .write.csv("plain-text-df/")
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +RecordLoader.loadArchives("example.warc.gz", sc)
For consistency, change to `example.arc.gz`?

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +RecordLoader.loadArchives("example.warc.gz", sc)
For consistency change to `example.arc.gz`?

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +RecordLoader.loadArchives("example.warc.gz", sc)
for consistency change to `example.arc.gz`?

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +  .write.csv("plain-text-date-filtered-2008-2015-df/")
Error

```
<pastie>:103: error: value DateComponent is not a member of org.apache.spark.sql.expressions.UserDefinedFunction
          .keepDateDF(List("2008","2015"), ExtractDateDF.DateComponent.YYYY)
                                                         ^
```

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +RecordLoader.loadArchives("example.warc.gz", sc)
change to `example.arc.gz`?

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +RecordLoader.loadArchives("example.warc.gz", sc)
change to `example.arc.gz`?

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +```
Leads to error:

```
<pastie>:111: error: overloaded method value filter with alternatives:
  (func: org.apache.spark.api.java.function.FilterFunction[org.apache.spark.sql.Row])org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] <and>
  (func: org.apache.spark.sql.Row => Boolean)org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] <and>
  (conditionExpr: String)org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] <and>
  (condition: org.apache.spark.sql.Column)org.apache.spark.sql.Dataset[org.apache.spark.sql.Row]
 cannot be applied to (Boolean)
          .filter($"language" == "fr")
           ^
```

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +RecordLoader.loadArchives("example.warc.gz", sc)
recommend changing to arc for consistency

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +  .saveAsTextFile("plain-html-rdd/")
✅

2020-01-17 16:35 UTC, ianmilligan1 commented on current/text-analysis.md
> +```
✅

2020-01-17 16:46 UTC, SamFritz reviewed
Added in review, mostly just addresses quick and minor fixes. Note: while reviewing, line #s are provided, especially in cases where comment was added below section that needs addressing (because I wasn't able to see the blue + button). In some cases there are questions on formatting.

My focus was on text rather then code pieces. Like @ianmilligan1 I'm happy to run through the code snippets for testing.

The documentation is looking fantastic @ruebot!!

2020-01-17 16:46 UTC, SamFritz commented on current/README.md
>  The Archives Unleashed Toolkit is an open-source platform for analyzing web archives built on [Apache Spark](http://spark.apache.org/), which provides powerful tools for analytics and data processing
Delete space proceeding paragraph

2020-01-17 16:46 UTC, SamFritz commented on current/README.md
>  If you want to learn more about [Apache Spark](https://spark.apache.org/), we highly recommend [Spark: The Definitive Guide](http://shop.oreilly.com/product/0636920034957.do)
Delete space proceeding paragraph

2020-01-17 16:46 UTC, SamFritz commented on current/README.md
>  Our documentation is divided into several main sections, which cover the Archives Unleashed Toolkit workflow from analyzing collections to understanding and working with the results.
Delete space proceeding paragraph

2020-01-17 16:46 UTC, SamFritz commented on current/README.md
Capitalize **Text** --> line 34 (Extract Plain text Filtered by Keyword)

2020-01-17 16:46 UTC, SamFritz commented on current/README.md
line 84 in Acknowledgments section: remove **and** before "the Faculty of Arts"

2020-01-17 16:46 UTC, SamFritz commented on current/README.md
>  The Archives Unleashed Toolkit is an open-source platform for analyzing web archives built on [Apache Spark](http://spark.apache.org/), which provides powerful tools for analytics and data processing
Although I'm not sure if maybe space formatting just looks off in the review panel. Doesn't seem to have leading spaces in the aut-docs page

2020-01-17 16:46 UTC, SamFritz commented on current/binary-analysis.md
I'm finding that in the Python DF we mention 'width' and 'height' will be extracted, but the example outputs don't have these columns - are the dimensions embedded in the columns that are shown?

2020-01-17 16:46 UTC, SamFritz commented on current/link-analysis.md
Line 19/20 - looks like there's an incomplete sentence. ends on however

2020-01-17 16:46 UTC, SamFritz commented on current/link-analysis.md
>  The format of this output is:
question: line 205 "- Field one: Crawldate" should it be `yyyyMMdd` or `yyyymmdd`?

2020-01-17 16:46 UTC, SamFritz commented on current/link-analysis.md
>  The format of this output is:
Also line 220, ExtractLinks --> `ExtractLinks` ?

2020-01-17 16:46 UTC, SamFritz commented on current/link-analysis.md
line 295: open-soure --> open-source

2020-01-17 16:46 UTC, SamFritz commented on current/standard-derivatives.md
>  sc.setLogLevel("INFO")
line 15 - should we add the `code` command (inline) for concatenation, as graph pass command is written directly below the paragraph?

2020-01-17 16:46 UTC, SamFritz commented on current/standard-derivatives.md
>  How do I extract binary information of PDFs, audio files, video files, word processor files, spreadsheet files, presentation program files, and text files to a CSV file, or into the [Apache Parquet](
"How do I extract binary information " --> "How do I extract **the** binary information"

2020-01-17 16:46 UTC, SamFritz commented on current/text-analysis.md
>  import io.archivesunleashed._
Line 12 --> capitalize Text (filtered by keyword)

2020-01-17 20:21 UTC, ianmilligan1 approved these changes

2020-01-17 20:22 UTC, ianmilligan1 commented
Looks good to me - I'll wait for @SamFritz's thumbs up and then I'm happy to merge.

2020-01-20 14:48 UTC, SamFritz commented
👍 good to go :)

2020-01-20 14:51 UTC, merged