Add Citation to Documentation: Issue 92
archivesunleashed/aut-docs pull request #93
Opened 2020-10-05 18:27 UTC by SamFritz

Forked aut-docs repo to create this PR, which addresses [issue 92](https://github.com/archivesunleashed/aut-docs/issues/92): 
- Creates a new heading on documentation home page (Citing Archives Unleashed)
- Described how cite Archives Unleashed (toolkit/cloud)

This PR implements work outlined in [AUT issue-497](https://github.com/archivesunleashed/aut/issues/497)

@ianmilligan1 @ruebot, happy to help with any changes of this implementation! Thanks for your review.

2020-10-05 18:30 UTC, ianmilligan1 approved these changes

2020-10-05 18:32 UTC, ianmilligan1 requested changes

2020-10-05 18:32 UTC, ianmilligan1 commented on docs/home.md
> +> Nick Ruest, Jimmy Lin, Ian Milligan, and Samantha Fritz. 2020. The Archives Unleashed Project: Technology, Process, and Community to Improve Scholarly Access to Web Archives. In _Proceedings of the
Oh I approved this too early. This is throwing a line length error. You'll need to break into different lines.

2020-10-05 18:32 UTC, ianmilligan1 commented on docs/home.md
> +Your citations help to further the recognition of using open-source tools for scientific inquiry, assists in growing the web archiving community, and acknowledges the efforts of contributors to this
Same here!

2020-10-05 19:26 UTC, ianmilligan1 approved these changes
Looks great! I think as it is the citation will only appear when we do our next documentation release; if we want to have this appearing immediately, the same changes also have to get mapped over to [this page](https://github.com/archivesunleashed/aut-docs/blob/main/website/versioned_docs/version-0.80.0/home.md) as well.

2020-10-07 16:05 UTC, SamFritz commented
Thanks @ruebot, just updating now! Thanks for your patience (seemed to have missed this notification).

2020-10-07 16:14 UTC, merged